### PR TITLE
Request to merge Dev

### PR DESCRIPTION
**Pull request by Kingstalux**
- In this task, we were working with the real live data from the SpaceX API. 
- The task was to build a web application for a company that provides commercial and scientific space travel services. 
- The application will allow users to book rockets and join selected space missions. 
- The Rockets section displays a list of all available SpaceX rockets. 
- Users can book each rocket by clicking the reservation button or canceling the previously made booking. 
- The Missions section displays a list of current missions along with their brief description and participation status. 
- There is also a button next to each mission that allows users to join the selected mission or leave the mission the user joined earlier. 
- The My Profile section displays all reserved rockets and space missions.

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [x] Please write unit tests with React Testing Library and Jest
- [x] I suggest that you remove unnecessary scripts in your README, and add stacks you used while building this project and how to get the application locally up and running step by step



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingstalux** [comment]
- Hello @DeliceLydia,  we've updated the README file as requested.
- As for the tests, it wasn't part of the requirements as there wasn't any kanban board card that required us to do tests.

**Review by ArthurGC — CHANGES_REQUESTED** [review]
# Required Changes ♻️ :warning: 
Hi Team,



## Aspects to improve ♻️

- [x] It would be better to write unit tests with React Testing Library and Jest. Following the rules, the next reviewers just check the requirements from the previous reviewer. Please, try to implement them. Sorry for the inconvenience (there isn't a card on the Kanban board for tests).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi  Team, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
